### ISSUE TITLE
Error when deobfuscating some files

### ISSUE THREAD

**Issue by VendorAttestation** [j4k0xb/webcrack#129]
### Describe the bug

Error when deobfuscating some files

### Expected Behaviour

Deobfus

### Code

```JavaScript
https://dmca.sh/WinO6/TIyUdoDu03.js
```

### Logs

```Text
none
```

**Comment by 0xdevalias** [comment]
Running the attached code on https://wakaru.vercel.app/

- [contentScript.js.txt](https://github.com/user-attachments/files/18839183/contentScript.js.txt)

```
SyntaxError: Invalid left-hand side in assignment expression. (1:793753)
    at a (unpacker.worker-DMr9faCP.js:174:11446)
    at gq.raise (unpacker.worker-DMr9faCP.js:176:19566)
    at gq.checkLVal (unpacker.worker-DMr9faCP.js:178:14074)
    at gq.parseMaybeAssign (unpacker.worker-DMr9faCP.js:178:83066)
    at gq.parseExpressionBase (unpacker.worker-DMr9faCP.js:178:81708)
    at unpacker.worker-DMr9faCP.js:178:81626
    at gq.allowInAnd (unpacker.worker-DMr9faCP.js:179:11729)
    at gq.parseExpression (unpacker.worker-DMr9faCP.js:178:81606)
    at gq.parseStatementContent (unpacker.worker-DMr9faCP.js:179:19368)
    at gq.parseStatementLike (unpacker.worker-DMr9faCP.js:179:16568)
```

```
hook.js:608 Error: Invalid left-hand side in assignment expression. (1:793753)
    at Worker.taskResultDispatch (main-2ZEBvJd8.js:778:34925)
```

![Image](https://github.com/user-attachments/assets/9318c72b-ca95-4067-a6c2-4385f1a1249c)

**Comment by j4k0xb** [comment]
"Error" in the title might be a bit misleading. There's no thrown error because webcrack/babel can recover from "technically invalid syntax" like `qZXTWe()=EpAebA`.
But it still fails to deobfuscate because support for this different obfuscator was never implemented.

**Comment by ptraced** [comment]
@j4k0xb any news on this? can provide more samples

**Comment by 0xdevalias** [comment]
> any news on this?

@ptraced I believe @j4k0xb [already answered this](https://github.com/j4k0xb/webcrack/issues/129#issuecomment-2664638834):

> it still fails to deobfuscate because support for this different obfuscator was never implemented

> Seems like a rare use case and has a simple enough structure that it could be done interactively like [#76 (comment)](https://github.com/j4k0xb/webcrack/issues/76#issuecomment-2115058516)
