### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'path')

### ISSUE THREAD

**Issue by Sorte1** [j4k0xb/webcrack#49]
### Describe the bug

While using the CLI or the npm package, i've ran into some issue trying to deobfuscate some source code.

it throws the following error:
TypeError: Cannot read properties of undefined (reading 'path')

mangling this file also seems to be an issue.

TypeError: Cannot read properties of undefined (reading 'add')
same error as in #41 

```js
let code = fs.readFileSync('source.js', 'utf8');

    webcrack(code, {
        unminify: true,
       //mangle: true,
        onProgress: progress => {
            console.log('Progress:', progress);
        },
        // mangle: true,
    }).then(result => {
        console.log(result);
    });
```
[source.zip](https://github.com/j4k0xb/webcrack/files/13921446/source.zip)

### Expected Behaviour

i would have expected the npm package and the cli to have deobfuscated and mangled without issues.

### Code

```JavaScript
too long... file is included in source.zip
```

### Logs

```Text
Progress: 0
progress: 12.5
Progress: 25
Progress: 37.5
Progress: 50
Progress: 62.5
Progress: 75
Progress: 87.5

TypeError: Cannot read properties of undefined (reading 'path')
    at file:///home/sorte/projects/Bot/ignore/node_modules/.pnpm/webcrack@2.12.0/node_modules/webcrack/dist/index.js:3600:26
    at Array.forEach (<anonymous>)TypeError: Cannot read properties of undefined (reading 'path')
    at file:///home/sorte/projects/test/node_modules/.pnpm/webcrack@2.12.0/node_modules/webcrack/dist/index.js:3600:26
    at Array.forEach (<anonymous>)
    at ImportExportManager.insertImportsAndExports (file:///home/sorte/projects/test/node_modules/.pnpm/webcrack@2.12.0/node_modules/webcrack/dist/index.js:3584:22)
    at new WebpackModule (file:///home/sorte/projects/test/node_modules/.pnpm/webcrack@2.12.0/node_modules/webcrack/dist/index.js:4197:31)
    at Object.CallExpression (file:///home/sorte/projects/test/node_modules/.pnpm/webcrack@2.12.0/node_modules/webcrack/dist/index.js:4287:27)
    at NodePath._call (/home/sorte/projects/test/node_modules/.pnpm/@babel+traverse@7.23.7/node_modules/@babel/traverse/lib/path/context.js:46:20)
    at NodePath.call (/home/sorte/projects/test/node_modules/.pnpm/@babel+traverse@7.23.7/node_modules/@babel/traverse/lib/path/context.js:36:17)
    at NodePath.visit (/home/sorte/projects/test/node_modules/.pnpm/@babel+traverse@7.23.7/node_modules/@babel/traverse/lib/path/context.js:82:31)
    at TraversalContext.visitQueue (/home/sorte/projects/test/node_modules/.pnpm/@babel+traverse@7.23.7/node_modules/@babel/traverse/lib/context.js:86:16)
    at TraversalContext.visitSingle (/home/sorte/projects/test/node_modules/.pnpm/@babel+traverse@7.23.7/node_modules/@babel/traverse/lib/context.js:65:19)
    at ImportExportManager.insertImportsAndExports (file:///home/sorte/projects/Bot/ignore/node_modules/.pnpm/webcrack@2.12.0/node_modules/webcrack/dist/index.js:3584:22)
    at new WebpackModule (file:///home/sorte/projects/Bot/ignore/node_modules/.pnpm/webcrack@2.12.0/node_modules/webcrack/dist/index.js:4197:31)
    at Object.CallExpression (file:///home/sorte/projects/Bot/ignore/node_modules/.pnpm/webcrack@2.12.0/node_modules/webcrack/dist/index.js:4287:27)
    at NodePath._call (/home/sorte/projects/Bot/ignore/node_modules/.pnpm/@babel+traverse@7.23.7/node_modules/@babel/traverse/lib/path/context.js:46:20)
    at NodePath.call (/home/sorte/projects/Bot/ignore/node_modules/.pnpm/@babel+traverse@7.23.7/node_modules/@babel/traverse/lib/path/context.js:36:17)
    at NodePath.visit (/home/sorte/projects/Bot/ignore/node_modules/.pnpm/@babel+traverse@7.23.7/node_modules/@babel/traverse/lib/path/context.js:82:31)
    at TraversalContext.visitQueue (/home/sorte/projects/Bot/ignore/node_modules/.pnpm/@babel+traverse@7.23.7/node_modules/@babel/traverse/lib/context.js:86:16)
    at TraversalContext.visitSingle (/home/sorte/projects/Bot/ignore/node_modules/.pnpm/@babel+traverse@7.23.7/node_modules/@babel/traverse/lib/context.js:65:19)
```

**Comment by j4k0xb** [comment]
Oops I published from the wrong branch last time
Fixed now in v2.12.1
